# Generated by Django 4.2.18 on 2025-01-31 09:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='core.category'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.event_image_file_path),
        ),
    ]
