# Generated by Django 4.2.18 on 2025-02-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_events_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_attendee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('organizer', 'Organizer'), ('superuser', 'Superuser')], default='attendee', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
