# Generated by Django 4.2.18 on 2025-02-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_is_superuser_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_attendee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_organizer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
