# Generated by Django 4.2.19 on 2025-02-11 06:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_eventimage_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to=core.models.event_image_file_path),
        ),
    ]
