# Generated by Django 4.2.19 on 2025-02-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_rating_unique_together_remove_rating_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
