# Generated by Django 4.2.19 on 2025-02-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_venue_eventsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='event',
        ),
        migrations.DeleteModel(
            name='EventSession',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
