# Generated by Django 4.2.19 on 2025-02-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_category_slug_remove_events_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='time',
            new_name='time_start',
        ),
        migrations.AddField(
            model_name='events',
            name='venue_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='venue_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='events',
            name='venue_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
