# Generated by Django 4.2.19 on 2025-02-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='validated_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
