# Generated by Django 4.2.19 on 2025-02-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ticket_validated_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='link',
        ),
    ]
