# Generated by Django 4.2.19 on 2025-02-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_events_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='common_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='vip_price',
            field=models.IntegerField(null=True),
        ),
    ]
