# Generated by Django 4.2.19 on 2025-02-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_events_common_price_events_vip_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
