# Generated by Django 4.2.19 on 2025-02-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='common_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='vip_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
